config/routes.rb
Rails.application.routes.draw do
    
    resources :sessions
    get 'profiles/login', to: 'sessions#new', as: 'login'
    delete '/sessions', to: 'sessions#destroy', as: 'end_session'
    
    resources :users do
      get '/trainer', to: 'users#trainer'
      get '/advicer', to: 'users#advicer'
      post '/coaches', to: 'coaches#create'
      delete '/coaches', to: 'coaches#destroy', as: 'delete_relationship'
      get '/profiles', to: 'profiles#show'
      get '/profiles/edit', to: 'profiles#edit'
      post '/profiles', to: 'profiles#update', as: 'workouts_profiles_update'
      
      resources :workouts do
        post '/pumps', to: 'pumps#create'
        post '/reviews', to: 'reviews#create'
      end
      resources :diets do
        post '/pumps', to: 'pumps#create'
        post '/reviews', to: 'reviews#create'
      end
    end
    resources :workouts
    resources :diets
  end

  

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update]
    
    def login
      @profile = User.new
    end
  
    def create
      @profile = User.new(user_params)
      if @profile.save
        redirect_to user_path(@profile)
      else
        render :login
      end
    end
  
    def show
      @current_user = User.find(session[:user_id])
      @workout = @user.workouts.sort_by do |workout|
        workout.created_at
      end.reverse
    end
  
    def edit
      @workouts = @user.workouts
    end
  
    def update
      if @user.update(user_params)
        redirect_to user_path(@user)
      else
        render :edit
      end
    end
  
  
  private
  
  def set_user
    @user = User.find(session[:user_id])
  end
  
  def user_params
    params.require(:user).permit(:name, :url, :bio, :username, :img, :address, :phone, :occupation,  :password, :password_confirmation, :search)
  end
end

app/helpers/fitness/profiles_helper.rb
module Fitness::ProfilesHelper
end

app/views/profiles/edit.html.erb
<section class="features-icons bg-light text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-layers m-auto text-primary"></i>
            </div>

<% if @user.errors.any?  %>
 <div id="error explanation">
 <h2>We found a few errors in your form:</h2>
 <ul>
 <% @user.errors.full_messages.each do |message| %>
   <li><%= message %></li>
 <% end  %>
 </ul>
<% end %>

<h3>Edit Profile:</h3>


<%= form_for @user, url: user_workouts_profiles_update_path, method: :post do |f| %>
<div class="form-group">
<%= f.label :name, "Name:" %><br>
<%= f.text_field :name %>
</div>
<div class="form-group">
<%= f.label :url, "URL:" %><br>
<%= f.text_field :url %>
</div>
<div class="form-group">
<%= f.label :bio, "Bio:" %><br>
<%= f.text_area :bio, maxlength: 200 %>
</div>
<div class="form-group">
<%= f.submit "Update Profile" %>
</div>
<% end  %>
<br>

<h4 class="workout-subtitle"> Delete A Workout:</h4>

<% @workouts.each do |workout| %>
  <div class="workout">
   <p><%= link_to workout.title, user_workout_path(@user.id, workout.id) %>
   <%= form_tag user_workout_path(workout.user, workout.id), method: "delete" do %>
<%= submit_tag "Delete" %></p>
  <% end %>
  </div>
<% end %>
</div>
</div>

</div>
</div>
</div>
</section>

app/views/profiles/login.html.erb
<div class="container">


<h1>Create Account</h1>
<%= form_for @profile, controller: 'profiles', action: 'create_account' do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :city %>
<%= f.text_field :city %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :professional_industry %>
<%= f.text_field :professional_industry %>

<%= f.label :bio %>
<%= f.text_field :bio %>

<%= f.label :url %>
<%= f.text_field :url %>

<%= f.collection_select :category_name, @categories, :itself, :itself%>

<%= f.submit %>
<% end  %>

<h1>Log In</h1>

<%= form_for @profile,  %>

</div>

app/views/profiles/show.html.erb
<div class="container">


<h1><%= @user.name %></h1>

<div class="">
  <% if @current_user.id != @user.id  %>
    <% if @current_user.trainer_ids.include?(@user.id)  %>
      <h4 class="copyright text-muted"><em>Added Coach</em></h4>

      <span>
      <%= form_for @current_user, url: user_delete_relationship_path(@current_user.id), method: :delete do |f| %>
      <%= f.hidden_field :trainer_id, value: @user.id %>
      <%= f.submit "Remove Coach" %>
      <% end %>
      </span>

    <% else %>
      <%= form_for @current_user, url: user_coach_path(@current_user.id), method: :post do |f| %>
      <%= f.hidden_field :trainer_id, value: @user.id %>
      <%= f.submit "Add Coach" %>
      <% end %>
    <% end %>
  <% else %>
      <%= link_to "Edit My Profile", user_profiles_edit_path(@user)  %> <br>
  <% end  %> <br>
</div>


<div class="">
  <img src= "<%= @user.url %>" alt= "user image" height="100" width="150"><br>
  <br>
  <h4 class="workout-subtitle">About me: <%= @user.bio %></h4><br>
</div>


<div class="container">
   <div class="row">
     <div class="col-lg-8 col-md-10 mx-auto">

<h2> Workouts : </h2>

<% @workouts and @workouts.each do |workout| %>
  <div class="workout-preview">
       <a href="<%= user_workouts_path(@user.id, workout.id)%>">
         <h4 class="workout-title">
          <%= workout.title %>
         </h4>
         <h5 class="workout-subtitle">

          Posted by <%= @user.name %> on <%= (workout.created_at.strftime("%B %d, %Y")) %> | <%= workout.content_type %>

         </h5>
       </a>
       <h6 class="workout-subtitle"><%=image_tag("pump.jpg", height: "40", width: "40")%> <%= workout.pumps.count %>&nbsp; | &nbsp;<%= image_tag("review.png", height: "40", width: "40") %> <%= workout.reviews.count %></h6>
     </div>
     <div class="lineb">

  </div>
<% end %>

   </div>
  </div>
</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link href="css/clean-blog.min.css" rel="stylesheet">