config/routes.rb
Rails.application.routes.draw do
    
    resources :sessions
    get 'profiles/login', to: 'sessions#new', as: 'login'
    delete '/sessions', to: 'sessions#destroy', as: 'end_session'
    
    resources :users do
      get '/trainer', to: 'users#trainer'
      get '/advicer', to: 'users#advicer'
      post '/coaches', to: 'coaches#create'
      delete '/coaches', to: 'coaches#destroy', as: 'delete_relationship'
      get '/profiles', to: 'profiles#show'
      get '/profiles/edit', to: 'profiles#edit'
      post '/profiles', to: 'profiles#update', as: 'workouts_profiles_update'
      
      resources :workouts do
        post '/pumps', to: 'pumps#create'
        post '/reviews', to: 'reviews#create'
      end
      resources :diets do
        post '/pumps', to: 'pumps#create'
        post '/reviews', to: 'reviews#create'
      end
    end
    resources :workouts
    resources :diets
  end

  

app/models/user.rb
class User < ApplicationRecord
  has_many :coaches
  has_many :workouts
  has_many :diets
  has_many :reviews
  has_secure_password

  def find_trainers
    trainer_ids = Coach.where("user_id = ?", self.id).pluck("trainer_id")
  
    trainer_objects = Array.new
     trainer_ids.each do |train|
         trainer_objects << User.find(train)
     end
     
     trainer_data = Hash.new
      trainer_objects.each do |train|
          latest_workout = train.workouts.last
          trainer_data[train.name] = {}
          trainer_data[train.name][:latest_workout_title] = latest_workout.title
          trainer_data[train.name][:latest_workout_date] = (latest_workout.created_at.strftime("%B %d, %Y"))
          trainer_data[train.name][:user_id] = latest_workout.user_id
          trainer_data[train.name][:workout_id] = latest_workout.id
          trainer_data[train.name][:review_count] = latest_workout.reviews.count
          trainer_data[train.name][:content_type] = latest_workout.content_type
     end
  
      trainer_data.sort_by do | name, latest_workout|
          latest_workout[:created_at]
      end
  end

  def find_dietitians
    dietitian_ids = Coach.where("user_id = ?", self.id).pluck("dietitian_id")
  
    dietitian_objects = Array.new
     dietitian_ids.each do |die|
         dietitian_objects << User.find(die)
     end
     
     dietitian_data = Hash.new
      dietitian_objects.each do |die|
          latest_workout = die.diets.last
          dietitian_data[die.name] = {}
          dietitian_data[die.name][:latest_diet_title] = latest_diet.title
          dietitian_data[die.name][:latest_diet_date] = (latest_diet.created_at.strftime("%B %d, %Y"))
          dietitian_data[die.name][:user_id] = latest_diet.user_id
          dietitian_data[die.name][:diet_id] = latest_diet.id
          dietitian_data[die.name][:review_count] = latest_diet.reviews.count
          dietitian_data[die.name][:content_type] = latest_diet.content_type
     end
  
      dietitian_data.sort_by do | name, latest_diet|
          latest_diet[:created_at]
      end
  end

    def trainer_ids
        trainer_ids = Coach.where("user_id = ?", self.id).pluck("trainer_id")
    end

    def dietitian_ids
        dietitian_ids = Diet.where("user_id = ?", self.id).pluck("dietitian_id")
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  skip_before_action :authenticate_user, only: [:new, :create]

  def show
    @trainer_hash = @user.find_trainers
    @trainer_count = @user.coaches.count
    @dietitian_hash = @user.find_dietitians
    @dietitian_count = @user.coaches.count
    @new_review = Review.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
   if @user.valid?
     @user.save
     session[:user_id] = @user.id
     redirect_to user_path(@user.id)
   else
     flash[:message] = @user.errors.full_messages
     redirect_to new_user_path
   end
  end


  def trainer
    @new_review = Review.new
    @content_types = ["Workout", "Diet"]
    @workouts = Workout.all
      if @workouts == nil
        @searched = false
      elsif params[:search] && @workouts.length >= 1
        @searched = true
      end
  end
  
  def advicer
    @new_review = Review.new
    @content_types = ["Workout", "Diet"]
    @diets = Diet.all
      if @diets == nil
        @searched = false
      elsif params[:search] && @diets.length >= 1
        @searched = true
      end
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :url, :bio, :username, :img, :address, :phone, :occupation,  :password, :password_confirmation, :search)
  end
end

app/helpers/fitness/users_helper.rb
module Fitness::UsersHelper
end

app/views/users/advice.html.erb
<div class="container">


<h1>Diets</h1>

<h4>Search by Content Type</h4>
<%= form_tag user_advice_path, method: :get do  %>
<%= select_tag :search, options_for_select(@content_types), selected: params[:search] %>
<%= submit_tag ("Search") %>
<% end  %>

<% if @searched == true %>
  <h5>Filtered By: <%= params[:search] %></h5>
  <% elsif @searched == false  %>
  <h5>No Results for <%= params[:search] %></h5>
<% end  %>

<div class="container">
   <div class="row">
     <div class="col-lg-8 col-md-10 mx-auto">

<% if @searched == true || @searched == nil %>

  <% @diets and @diets.each do |diet| %>
    
    <!--BEGIN local variablse to name author and current user for modal-->
    <%@dietitian_id = diet.user_id %>
    <% @current_user = session[:user_id]%>
    <% @diet_modal = diet.id%>
    <!--END local variable to name author and current for modal-->
    <!--BEGIN create post link on discover page with information-->
    <div class="diet-preview">
         <a href="#<%=@diet_modal%>Modal" data-toggle="modal">
           <h4 class="diet-title">
          
            <%= diet.title %>
           </h4>
           <h5 class="diet-subtitle">

           Created by <%= User.find(diet.user_id).name %> on <%= (diet.created_at.strftime("%B %d, %Y")) %> | <%= diet.content_type %>

           </h5>
         </a>
         <h6 class="diet-subtitle"><%=image_tag("pump.png", height: "40", width: "40")%> <%= diet.pumps.count %>&nbsp; | &nbsp;<%= image_tag("review.png", height: "40", width: "40") %> <%= diet.reviews.count %></h6>
       </div>
       <div class="lineb">
    </div>
    <!--END create diet link on discover page with information-->

    <!-- BEGIN Modal for diet details  -->
    <div class="modal" id="<%=@diet_modal%>Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><h4 class= "diet-subtitle">
              <h3><%= diet.title %> </h3>
            Created By: <%= link_to User.find(@dietitian_id).name, user_profiles_path(User.find(@dietitian_id)) %>
            on <%= (diet.created_at.strftime("%B, %d, %Y")) %> |
             <%= link_to diet.content_type,diet.content_link, target: :_blank %>
             <h5><%= link_to image_tag("pump.png", height: "45", width: "45"), user_diet_pumps_path(@current_user, diet.id), method: :post, controller: 'pumps'%> <%= diet.pumps.count %> &nbsp; | &nbsp;
              <%= image_tag("review.png", height: "45", width: "45")%> <%= diet.reviews.count %></h5>
            </h4>

          </div>
          <div class="modal-body">
              <h4>
              Description: <%= diet.description %> <br>
              </h4>
              <br>
              <h4>Reviews:</h4>
             <% diet.reviews.each do |review| %>
               <div class="container please_align">
                 <div class="dialogbox">
                   <div class="body">
                     <span class="tip tip-up"></span>
                     <div class="message">

                   <span class="review_header"><%= review.find_user %> - <%= (review.created_at.strftime("%B %d, %Y")) %></span><br><span>
                   <%= review.text %></span>
                   </div>
                 </div>
               </div>
             </div>
                <% end %>

                <div class=" container please_align">
                  <h5>Add Review:</h5>
                  <%= form_for @new_review, url: user_diet_reviews_path(@current_user, diet.id) do |f| %>
                  <%= f.text_area :text, maxlength: 200 %> <br>
                  <%= f.label :text, "200 characters", class:"diet-subtitle" %> <br>
                  <br>
                  <%= f.submit "Create Review" %>
                  <% end  %>
                </div>
                </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <!-- END Modal for diet details -->


  <% end %>
<% end %>

   </div>
  </div>
</div>

</div>

app/views/users/new.html.erb
<div class="container">


<% if flash[:message] %>
  <%=  flash[:message].each do |message| %>
  <div class="text-center">
    <%= message %>
  </div>
  <% end %>
<% end  %>

<div class="row form-group justify-center-content">
  <div class="col-sm-12 col-md-12 col-lg-12 offset-sm-4 offset-md-4 offset-lg-4 text-center mx-auto ">
    <%= form_for @user, url: users_path do |f| %>

  <div class="form-group">
    <%= label_tag :name, "Name:" %><br>
    <%= f.text_field :name%>
  </div>
  <div class="form-group">
    <%= label_tag :username, "Username:" %><br>
    <%= f.text_field :username %>
  </div>
  <div class="form-group">
    <%= label_tag :password, "Password:" %><br>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <label>Password Confirmation:</label><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-group">
    <%= label_tag :url, "URL:" %><br>
    <%= f.text_field :url %>
  </div>
  <div class="form-group">
    <%= label_tag :phone, "Phone:" %><br>
    <%= f.telephone_field :phone %>
  </div>
  <div class="form-group">
    <%= label_tag :bio, "Bio:" %><br>
    <%= f.text_area :bio, maxlength: 200 %>
  </div>
  <div class="form-group">
    <%= label_tag :img, "Photo:" %><br>
    <%= f.text_field :img %>
  </div>
    <%= f.submit "Create Account"%>

  <% end %>

  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">

<% if @user.id == session[:user_id] %>
  <h1>Welcome, <%= @user.name %>!</h1>
<% else %>
  <h1><%= @user.name %></h1>
<% end %>

<p class="copyright text-muted">Diets: <%= @dietitian_count %> | Coaches: <%= @trainer_count %></p>
<div class="container">
   <div class="row">
     <div class="col-lg-8 col-md-8 mx-auto">

<h2>My Diets and Workouts:</h2>

<% if @trainer_count == 0 %>
<h3>Your feed is empty! <%= link_to "Click", user_trainer_path(@user) %> to find coaches.</h3>
<% end %>

<% @trainer_hash.each do |trainer, workout_data| %>

  <!-- BEGIN LOCAL VARIABLES JUST FOR MODAL-->
  <%@training_id = workout_data[:user_id]%>
  <% @current_user = session[:user_id]%>
  <% @workout_modal = workout_data[:workout_id]%>
  <% @workout = Workout.find(workout_data[:workout_id])%>
  <!-- END LOCAL VARIABLES JUST FOR MODAL-->

<div class="workout-preview">
     <a href="#<%=@workout_modal%>Modal" data-toggle="modal">
       <h4 class="workout-title">
        <%= workout_data[:latest_workout_title] %>
       </h4>
       <h5 class="workout-subtitle">

         Created by <%= trainer %> on <%= workout_data[:latest_workout_date] %> | <%= workout_data[:content_type] %>

       </h5>
     </a>
     <h6 class="workout-subtitle"><%=image_tag("pump.png", height: "40", width: "40")%> <%= workout_data[:pump_count] %>&nbsp; | &nbsp;<%= image_tag("review.png", height: "40", width: "40") %> <%= workout_data[:review_count] %></h6>
   </div>
   <div class="lineb">
   </div>


   <!-- BEGIN Modal for workout details  -->

   <!-- BEGIN LOCAL VARIABLES JUST FOR MODAL-->
   <%@training_id = workout_data[:user_id]%>
   <% @current_user = session[:user_id]%>
   <% @workout_modal = workout_data[:workout_id]%>
   <% @workout = Workout.find(workout_data[:workout_id])%>
   <!-- END LOCAL VARIABLES JUST FOR MODAL-->

   <div class="modal" id="<%=@workout_modal%>Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
     <div class="modal-dialog" role="document">
       <div class="modal-content">
         <div class="modal-header">
           <h5 class="modal-title" id="exampleModalLabel"><h4 class= "workout-subtitle">
             <h3><%= @workout.title %> </h3>
           Posted By: <%= link_to User.find(@training_id).name, user_profiles_path(User.find(@training_id)) %>
           on <%= (@workout.created_at.strftime("%B, %d, %Y")) %> |
            <%= link_to @workout.content_type,@workout.content_link, target: :_blank %>
            <h5><%= link_to image_tag("pump.png", height: "45", width: "45"), user_workout_pumps_path(@current_user, @workout.id), method: :post, controller: 'pumps'%> <%= @workout.pumps.count %> &nbsp; | &nbsp;
             <%= image_tag("review.png", height: "45", width: "45")%> <%= @workout.reviews.count %></h5>
           </h4>

         </div>
         <div class="modal-body">
             <h4>
             Description: <%= @workout.description %> <br>
             </h4>
             <br>
             <h4>Reviews:</h4>
            <% @workout.reviews.each do |review| %>
              <div class="container please_align">
                <div class="dialogbox">
                  <div class="body">
                    <span class="tip tip-up"></span>
                    <div class="message">

                  <span class="review_header"><%= review.find_user %> - <%= (review.created_at.strftime("%B %d, %Y")) %></span><br><span>
                  <%= review.text %></span>
                  </div>
                </div>
              </div>
            </div>
               <% end %>

               <div class=" container please_align">
                 <h5>Add Review:</h5>
                 <%= form_for @new_review, url: user_workout_reviews_path(@current_user, @workout.id) do |f| %>
                 <%= f.text_area :text, maxlength: 200 %> <br>
                 <%= f.label :text, "Be Nice!", class:"workout-subtitle" %> <br>
                 <br>
                 <%= f.submit "Create Review" %>
                 <% end  %>
               </div>
               </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
         </div>
       </div>
     </div>
   </div>
   <!-- END Modal for workout details -->

<% end %>

   </div>
  </div>
</div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link href="css/clean-blog.min.css" rel="stylesheet">

app/views/users/trainer.html.erb
<div class="container">


<h1>Trainers</h1>

<h4>Search by Content Type</h4>
<%= form_tag user_trainer_path, method: :get do  %>
<%= select_tag :search, options_for_select(@content_types), selected: params[:search] %>
<%= submit_tag ("Search") %>
<% end  %>

<% if @searched == true %>
  <h5>Filtered By: <%= params[:search] %></h5>
  <% elsif @searched == false  %>
  <h5>No Results for <%= params[:search] %></h5>
<% end  %>

<div class="container">
   <div class="row">
     <div class="col-lg-8 col-md-10 mx-auto">

<% if @searched == true || @searched == nil %>

  <% @workouts and @workouts.each do |workout| %>
    
    <!--BEGIN local variablse to name author and current user for modal-->
    <%@trainer_id = workout.user_id %>
    <% @current_user = session[:user_id]%>
    <% @workout_modal = workout.id%>
    <!--END local variable to name author and current for modal-->
    <!--BEGIN create post link on discover page with information-->
    <div class="workout-preview">
         <a href="#<%=@workout_modal%>Modal" data-toggle="modal">
           <h4 class="workout-title">
          
            <%= workout.title %>
           </h4>
           <h5 class="workout-subtitle">

           Created by <%= User.find(workout.user_id).name %> on <%= (workout.created_at.strftime("%B %d, %Y")) %> | <%= workout.content_type %>

           </h5>
         </a>
         <h6 class="workout-subtitle"><%=image_tag("pump.png", height: "40", width: "40")%> <%= workout.pumps.count %>&nbsp; | &nbsp;<%= image_tag("review.png", height: "40", width: "40") %> <%= workout.reviews.count %></h6>
       </div>
       <div class="lineb">
    </div>
    <!--END create workout link on discover page with information-->

    <!-- BEGIN Modal for workout details  -->
    <div class="modal" id="<%=@workout_modal%>Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel"><h4 class= "workout-subtitle">
              <h3><%= workout.title %> </h3>
            Created By: <%= link_to User.find(@trainer_id).name, user_profiles_path(User.find(@trainer_id)) %>
            on <%= (workout.created_at.strftime("%B, %d, %Y")) %> |
             <%= link_to workout.content_type,workout.content_link, target: :_blank %>
             <h5><%= link_to image_tag("pump.png", height: "45", width: "45"), user_workout_pumps_path(@current_user, workout.id), method: :post, controller: 'pumps'%> <%= workout.pumps.count %> &nbsp; | &nbsp;
              <%= image_tag("review.png", height: "45", width: "45")%> <%= workout.reviews.count %></h5>
            </h4>

          </div>
          <div class="modal-body">
              <h4>
              Description: <%= workout.description %> <br>
              </h4>
              <br>
              <h4>Reviews:</h4>
             <% workout.reviews.each do |review| %>
               <div class="container please_align">
                 <div class="dialogbox">
                   <div class="body">
                     <span class="tip tip-up"></span>
                     <div class="message">

                   <span class="review_header"><%= review.find_user %> - <%= (review.created_at.strftime("%B %d, %Y")) %></span><br><span>
                   <%= review.text %></span>
                   </div>
                 </div>
               </div>
             </div>
                <% end %>

                <div class=" container please_align">
                  <h5>Add Review:</h5>
                  <%= form_for @new_review, url: user_workout_reviews_path(@current_user, workout.id) do |f| %>
                  <%= f.text_area :text, maxlength: 200 %> <br>
                  <%= f.label :text, "200 characters", class:"workout-subtitle" %> <br>
                  <br>
                  <%= f.submit "Create Review" %>
                  <% end  %>
                </div>
                </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <!-- END Modal for workout details -->


  <% end %>
<% end %>

   </div>
  </div>
</div>

</div>