config/routes.rb
Rails.application.routes.draw do
    
    resources :sessions
    get 'profiles/login', to: 'sessions#new', as: 'login'
    delete '/sessions', to: 'sessions#destroy', as: 'end_session'
    
    resources :users do
      get '/trainer', to: 'users#trainer'
      get '/advicer', to: 'users#advicer'
      post '/coaches', to: 'coaches#create'
      delete '/coaches', to: 'coaches#destroy', as: 'delete_relationship'
      get '/profiles', to: 'profiles#show'
      get '/profiles/edit', to: 'profiles#edit'
      post '/profiles', to: 'profiles#update', as: 'workouts_profiles_update'
      
      resources :workouts do
        post '/pumps', to: 'pumps#create'
        post '/reviews', to: 'reviews#create'
      end
      resources :diets do
        post '/pumps', to: 'pumps#create'
        post '/reviews', to: 'reviews#create'
      end
    end
    resources :workouts
    resources :diets
  end

  

app/models/diet.rb
class Diet < ApplicationRecord
    belongs_to :user
    has_many :reviews
    has_many :pumps
  
    def sorted_reviews
      self.reviews.sort_by do |review|
        review.created_at
      end.reverse
    end
  
    def self.search(search)
      if search #if the user searched
        @reviews = self.where(content_type: search)
        if @reviews.length >= 1 #if at least one review returned
          @reviews
        else
          @reviews = nil
        end
      else
        @reviews = Review.all #if no search value return all 
      end
    end
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
    class WorkoutsController < ApplicationController
        before_action :set_diet, only: [:destroy, :show]
    
      def index
        @user = User.find(params[:user_id])
        @diets = @user.diets
      end
    
      def destroy
        @user = User.find(params[:user_id])
        @diet.destroy
        redirect_to user_profiles_edit_path(@user)
      end
    
      def show
        @advice_id = Diet.find(params[:id]).user_id
        @new_review = Review.new
        @reviews = @diet.sorted_reviews
        @current_user = session[:user_id]
      end
    
      def new
        @diet = Diet.new
        @user = User.find(session[:user_id])
        @content_types = ["Workout", "Diet"]
      end
    
      def create
        @user = User.find(session[:user_id])
        @diet = Diet.new(diet_params)
        @user.diets << @diet
        if @diet.save
          @user.save
          redirect_to user_profiles_path(:user_id)
        else
          render :new
        end
      end
    
      private
      def set_diet
        @diet = Diet.find(params[:id])
      end
    
      def diet_params
        params.require(:diet).permit(:title, :description, :content_link, :content_type, :user_id)
      end
    end
    
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/fitness/diets_helper.rb
module Fitness::DietsHelper
end

app/views/diets/new.html.erb
<h1>Become a Dietitian</h1>

<%= form_for @workout, url: user_diets_path([:user_id]) do |f|  %>
 <%= f.label :title, "Diet Type:" %><br>
 <%= f.text_field :title  %> <br>
<br>
 <%= f.label :description, "Description:" %><br>
 <%= f.text_field :description  %> <br>
<br>
 <%= f.label :content_link, "Content Link:" %><br>
 <%= f.text_field :content_link  %> <br>
<br>
 <%= f.label :content_type, "Content Type:" %><br>
 <%= f.collection_select :content_type, @content_types, :to_s, :to_s, include_blank: false %><br>
<br>
<%= f.submit %>
<br>
<% end  %>

app/views/diets/show.html.erb
<div class="container">

<h1><%= @diet.title %> </h1>

<div>
  <h4 class= "diet-subtitle">
  Posted By: <%= link_to User.find(@dietitian_id).name, user_profiles_path(User.find(@dietitian_id)) %>
  on <%= (@diet.created_at.strftime("%B, %d, %Y")) %> |
   <%= link_to @diet.content_type,@diet.content_link, target: :_blank %>
  </h4>
  <h4><%= link_to image_tag("pump.png", height: "45", width: "45"), user_diet_pumps_path(@current_user, @diet.id), method: :post, controller: 'pumps'%> <%= @diet.pumps.count %> &nbsp; | &nbsp;
   <%= image_tag("review.png", height: "45", width: "45")%> <%= @diet.reviews.count %></h4>
</div>
<div>
   <h4>
   Description: <%= @diet.description %> <br>
   </h4>
   <br>
   <h4>Reviews:</h4>
  <% @reviews.each do |review| %>
    <div class="container please_align">
      <div class="dialogbox">
        <div class="body">
          <span class="tip tip-up"></span>
          <div class="message">

        <span class="review_header"><%= review.find_user %> - <%= (review.created_at.strftime("%B %d, %Y")) %></span><br><span>
  	    <%= review.text %></span>
        </div>
      </div>
    </div>
  </div>
     <% end %>



<div class=" container please_align">
  <h5>Add Review:</h5>
  <%= form_for @new_review, url: user_diet_reviews_path(@current_user, @diet.id) do |f| %>
  <%= f.text_area :text, maxlength: 200 %> <br>
  <%= f.label :text, "Be Nice", class:"diet-subtitle" %> <br>
  <br>
  <%= f.submit "Create review" %>
  <% end  %>
</div>
</div>
</div>