config/routes.rb
Rails.application.routes.draw do
    
    resources :sessions
    get 'profiles/login', to: 'sessions#new', as: 'login'
    delete '/sessions', to: 'sessions#destroy', as: 'end_session'
    
    resources :users do
      get '/trainer', to: 'users#trainer'
      get '/advicer', to: 'users#advicer'
      post '/coaches', to: 'coaches#create'
      delete '/coaches', to: 'coaches#destroy', as: 'delete_relationship'
      get '/profiles', to: 'profiles#show'
      get '/profiles/edit', to: 'profiles#edit'
      post '/profiles', to: 'profiles#update', as: 'workouts_profiles_update'
      
      resources :workouts do
        post '/pumps', to: 'pumps#create'
        post '/reviews', to: 'reviews#create'
      end
      resources :diets do
        post '/pumps', to: 'pumps#create'
        post '/reviews', to: 'reviews#create'
      end
    end
    resources :workouts
    resources :diets
  end

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="Trainer" content="">

  <title>Fitness - Creating a Healthy Lifestyle</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap core CSS -->
  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>
  <!-- Navigation -->

  <% if session[:user_id] != nil %>
  <% @current_user = User.find(session[:user_id]) %>

  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <p class="copyright logout">
        <span>Hello <%=@current_user.name %></span><br>
        <%= form_for @current_user, url: user_path(@current_user), method: :get do |f| %>
        <%= f.submit "Homepage", class: "copyright logout" %>
        <% end %>
        <%= form_for @current_user, url: user_profiles_path(session[:user_id]), method: :get do |f| %>
        <%= f.submit "View Profile", class: "copyright logout" %>
        <% end %>

        <%= form_for @current_user, url: new_workout_path(session[:user_id]), method: :get do |f| %>
        <%= f.submit "Become a Trainer", class: "copyright logout" %>
        <% end %>

     
        <%= form_for @current_user, url: user_trainer_path(@current_user), method: :get do |f| %>
        <%= f.submit "Workouts", class: "copyright logout" %>
        <% end %>
      

        <%= form_for @current_user, url: end_session_path, method: :delete do |f| %>
        <%= f.submit "Logout", class: "copyright logout" %>
        <% end %>

      </p>
    </div>
  </nav>
  <%end %>

  <!-- Page Header -->

  <header class="masthead" style="background-image: url(<%= asset_path('home.png')%>)"">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 mx-auto">
          <div class="site-heading">
            <h1>Fitness</h1>
            <span class="subheading">Creating a Healthy Lifestyle</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
    <%= yield %>
        <!-- Pager -->

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 mx-auto">
          <p class="copyright text-muted"></p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"/>
</html>